// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpkosdeadxxorvblnmxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indwa29zZGVhZHh4b3J2YmxubXh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDUyNjIsImV4cCI6MjA2MzU4MTI2Mn0.v29LVar0BdStEw41fUyxl4xRwIyUfNp3xgdUrZaXorg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);